pub const Token = struct {
    const Type = enum {
        Eof,
        Extern,
        Def,
        Proc,
        If,
        Do,
        For,
        Var,
        Number,
        String,
        Macro,
        Ident,
        Bracket,
        Paren,
        Op,
        Struct,
        Prop,
        Lambda,
        Error,
        Global,
        Func,
        Const,
        Import,
        Embed,
        While,
    };

    type: Type,
    pos: u64,
    value: []const u8,
};
